import Testing
@testable import DBusCodegen

@Suite
struct IntegrationTests {
  static let xml = """
    <node>
      <interface name="org.bluez.GattCharacteristic1">
        <method name="ReadValue">
          <arg name="options" type="a{sv}" direction="in"/>
          <arg name="value" type="ay" direction="out"/>
        </method>
        <property name="UUID" type="s" access="read"/>
        <signal name="PropertiesChanged">
          <arg name="interface_name" type="s"/>
          <arg name="changed_properties" type="a{sv}"/>
        </signal>
      </interface>
    </node>
    """

  @Test func producesValidSwiftSource() throws {
    let source = try Codegen.generate(xml: Self.xml, moduleName: nil)
    // File header
    #expect(source.contains("// Generated by dbus-codegen"))
    #expect(source.contains("import DBUS"))
    #expect(source.contains("DBusCodegenError"))
    // Client
    #expect(source.contains("public protocol OrgBluezGattCharacteristic1"))
    #expect(source.contains("public struct OrgBluezGattCharacteristic1Proxy"))
    // Server
    #expect(source.contains("public protocol OrgBluezGattCharacteristic1Handler"))
    #expect(source.contains("func makeInterface()"))
    // Signal
    #expect(source.contains("func propertiesChanged()"))
    #expect(source.contains("AddMatch"))
  }

  @Test func writeOnlyPropertyOmitsGetterFromProtocol() throws {
    let xml = """
      <node>
        <interface name="org.example.WriteOnly">
          <property name="Secret" type="s" access="write"/>
        </interface>
      </node>
      """
    let source = try Codegen.generate(xml: xml, moduleName: nil)
    // Must not emit a getter requirement for a write-only property
    #expect(!source.contains("var secret"))
    // Must emit the setter requirement
    #expect(source.contains("func setSecret"))
  }

  @Test func serverSetterClosureWiredForReadWriteProperty() throws {
    let xml = """
      <node>
        <interface name="org.example.RW">
          <property name="Count" type="u" access="readwrite"/>
        </interface>
      </node>
      """
    let source = try Codegen.generate(xml: xml, moduleName: nil)
    // Setter bridge must be present in makeInterface
    #expect(source.contains("set: { [self]"))
    #expect(source.contains("setCount"))
  }

  @Test func emptyInterfaceListProducesHeaderOnly() throws {
    let source = try Codegen.generate(xml: "<node/>", moduleName: nil)
    #expect(source.contains("// Generated by dbus-codegen"))
  }

  @Test func modulenameAppearsInHeader() throws {
    let source = try Codegen.generate(xml: "<node/>", moduleName: "MyModule")
    #expect(source.contains("MyModule"))
  }
}
