public enum Codegen {
  public struct Options: Sendable {
    public var moduleName: String?
    public init(moduleName: String? = nil) {
      self.moduleName = moduleName
    }
  }

  public static func generate(xml: String, moduleName: String?) throws -> String {
    try generate(xml: xml, options: Options(moduleName: moduleName))
  }

  public static func generate(xml: String, options: Options = Options()) throws -> String {
    let node = try DBusParser.parse(xml: xml)
    var writer = CodeWriter()

    // File header
    let moduleNote = options.moduleName.map { " (module: \($0))" } ?? ""
    writer.writeLine("// Generated by dbus-codegen\(moduleNote). Do not edit.")
    writer.writeLine("import DBUS")
    writer.writeLine()
    writer.writeLine("private enum DBusCodegenError: Error { case typeMismatch }")
    writer.writeLine()

    for interface in node.interfaces {
      writer.writeLine("// MARK: - \(interface.name)")
      writer.writeLine()
      generateClient(interface: interface, into: &writer)
      ServerGenerator.generate(interface: interface, into: &writer)
      writer.writeLine()
    }

    return writer.result
  }

  private static func generateClient(interface: DBusInterface, into writer: inout CodeWriter) {
    let prefix = TypeMapper.interfacePrefix(interface.name)

    // Protocol: methods + properties + signal stubs
    writer.writeLine("public protocol \(prefix): Sendable {")
    writer.indent { w in
      for method in interface.methods {
        w.writeLine(clientMethodSignature(method))
      }
      for property in interface.properties {
        if property.access == .read || property.access == .readWrite {
          w.writeLine(
            "var \(TypeMapper.swiftIdentifier(property.name)): \(TypeMapper.swiftType(for: property.type)) { get async throws }"
          )
        }
        if property.access == .readWrite || property.access == .write {
          w.writeLine(
            "func set\(property.name)(_ newValue: \(TypeMapper.swiftType(for: property.type))) async throws"
          )
        }
      }
      SignalGenerator.generateProtocolMembers(interface: interface, into: &w)
    }
    writer.writeLine("}")
    writer.writeLine()

    // Proxy struct: methods + properties + signal impls
    writer.writeLine("public struct \(prefix)Proxy: \(prefix) {")
    writer.indent { w in
      w.writeLine("private let connection: DBusClient.Connection")
      w.writeLine("private let destination: String")
      w.writeLine("private let path: String")
      w.writeLine()
      w.writeLine(
        "public init(connection: DBusClient.Connection, destination: String, path: String) {")
      w.indent { w2 in
        w2.writeLine("self.connection = connection")
        w2.writeLine("self.destination = destination")
        w2.writeLine("self.path = path")
      }
      w.writeLine("}")
      for method in interface.methods {
        w.writeLine()
        ClientGenerator.generateMethodImpl(method, interfaceName: interface.name, into: &w)
      }
      for property in interface.properties {
        w.writeLine()
        ClientGenerator.generatePropertyImpl(property, interfaceName: interface.name, into: &w)
      }
      if !interface.signals.isEmpty {
        w.writeLine()
        SignalGenerator.generateProxyImplementations(interface: interface, into: &w)
      }
    }
    writer.writeLine("}")
    writer.writeLine()
  }

  private static func clientMethodSignature(_ method: DBusMethod) -> String {
    let name = TypeMapper.swiftIdentifier(method.name)
    let params = method.inArgs.map { arg in
      "\(TypeMapper.swiftIdentifier(arg.name)): \(TypeMapper.swiftType(for: arg.type))"
    }.joined(separator: ", ")
    let returnClause: String
    switch method.outArgs.count {
    case 0: returnClause = ""
    case 1: returnClause = " -> \(TypeMapper.swiftType(for: method.outArgs[0].type))"
    default:
      let tuple = method.outArgs.map { arg in
        "\(TypeMapper.swiftIdentifier(arg.name)): \(TypeMapper.swiftType(for: arg.type))"
      }.joined(separator: ", ")
      returnClause = " -> (\(tuple))"
    }
    return "func \(name)(\(params)) async throws\(returnClause)"
  }
}
